### ISSUE TITLE
Will a fence instruction be executed after the mseccfg is modified?

### ISSUE THREAD

**Issue by EJLife** [riscv/riscv-tee#17]
Hi,
I see the description "This is accomplished by  executing an SFENCE.VMA instruction with ..., after the PMP CSRs are written" in the riscv-privileged-20211206. But I'm not see similar behavior in smepmp spec?  I think mseccfg.MML also will influence the check of physical addresses? 

Thanks,
David

**Comment by pdonahue-ventana** [comment]
The requirement is that "when the PMP settings are modified" then software must execute a particular SFENCE.VMA instruction.  I think that MML is part of "the PMP settings" and that it is one of "the PMP CSRs" that are written so you'd need the SFENCE.VMA.  Clarification would be helpful since others may assume that, absent an explicit requirement, only the PMP subset of ePMP follows that rule.

**Comment by EJLife** [comment]
Thanks Paul! Your clarification really helped me.

**Comment by EJLife** [comment]
> The requirement is that "when the PMP settings are modified" then software must execute a particular SFENCE.VMA instruction. I think that MML is part of "the PMP settings" and that it is one of "the PMP CSRs" that are written so you'd need the SFENCE.VMA. Clarification would be helpful since others may assume that, absent an explicit requirement, only the PMP subset of ePMP follows that rule.

Thanks Paul! Your clarification really helped me.
